### ISSUE TITLE
Base Goerli Support on SDK

### ISSUE THREAD

**Issue by blobitty** [0xSplits/splits-sdk#19]
Is it possible to get Base Goerli support in the SDK library? I see that a subgraph is available [here](https://api.thegraph.com/subgraphs/name/0xsplits/splits-subgraph-base-goerli/graphql?query=) so that data should be available if assume correctly?

**Comment by mihoward21** [comment]
Yes, can get that added for you soon. Will let you know when it's available.

**Comment by mihoward21** [comment]
Ok @blobitty this is available on the latest release (3.2.3). Let us know if you are having any issues with it.
