### ISSUE TITLE
Add support for vesting

### ISSUE THREAD

**Issue by akshatcx** [0xSplits/splits-sdk#2]
Is there a plan to add support for vesting type splits?

**Comment by mihoward21** [comment]
Just to be clear, you are referring to the vesting streams available in our app (like [this one](https://app.0xsplits.xyz/accounts/0xF29Ff96aaEa6C9A1fBa851f74737f3c069d4f1a9/))?

We are planning to add support for those to the SDK. Mostly just haven't been prioritizing it. Could probably get it added soon.

Is there specific functionality you are looking for? Could prioritize that if needed.

**Comment by akshatcx** [comment]
Yes, I was talking about that. No specific functionality as such.

Was just curious, is the sdk being used in the frontend application?

**Comment by mihoward21** [comment]
Yes we are using the sdk for our frontend. Obviously there is some functionality in the frontend that does not exist in the sdk, though we're working on adding all of that functionality that makes sense.

Have the vesting stuff in the latest beta of the sdk if you want to download that. Should have it in the latest production version and on our docs this week.

**Comment by mihoward21** [comment]
This is live now and up on our docs: https://docs.0xsplits.xyz/sdk-info/vesting

Let us know if there's anything else you are looking for!
