### ISSUE TITLE
Safe app broken

### ISSUE THREAD

**Issue by czepluch** [0xSplits/splits-sdk#56]
Both on Brave and Firefox the Split app seems to be broken when used from within Gnosis Safe's "app" functionality.

**Comment by mihoward21** [comment]
Hi @czepluch , thanks for reporting this. That should be fixed now, please let us know if you are still seeing any issues there.

**Comment by czepluch** [comment]
Great, thanks. Just checked and can confirm that it does indeed seem to work.
