### ISSUE TITLE
How to make split cancellable

### ISSUE THREAD

**Issue by pukykoi** [0xSplits/splits-sdk#6]
I want to make a split immutable (percentage of share cannot be changed), but still leave the possibility for a controller, to cancel the split at any point in time.   
How would I do this?

**Comment by wminshew** [comment]
Hi -- what does "cancel" mean in this context?

**Comment by pukykoi** [comment]
Given three payees, payee A, payee B, payee C.   
Payee A receives 50% of any payment. It is also the controller.   
Payee B and Payee C receive 25% each.   

Once the split is issued, payee A cannot modify the share of any payee. Thus, the split is now immutable.      
However, if at any point the payees come to a disagreement, I want payee A to "pull the plug", in a way where none of the future payments will be distributed to any payee.  For example, automatically drop the share of the three payees to zero.    

In this case, either the transaction is cancelled and refunded to the issuer (the split is cancelled), or if not possible, stuck in a fund, until the three payees come to a consensus.

**Comment by wminshew** [comment]
Thank you for the context; responded on discord but following up here as well for posterity. The off-the-shelf splits contracts we provide can't handle this use case today, but there are many ways to solve it (with our contracts as well as with others) if you're willing to deploy your own contracts
